-- ============================================================================
-- Bolão Copa 2026 — Nomes dos 48 times em português (BR).
-- Display-only e idempotente (CASE por code). NÃO afeta o de-para da ESPN,
-- que casa por matches.espn_event_id, não por nome. Re-executável.
-- ============================================================================
update public.teams set name = case code
  when 'MEX' then 'México'
  when 'RSA' then 'África do Sul'
  when 'KOR' then 'Coreia do Sul'
  when 'CZE' then 'Tchéquia'
  when 'CAN' then 'Canadá'
  when 'BIH' then 'Bósnia e Herzegovina'
  when 'QAT' then 'Catar'
  when 'SUI' then 'Suíça'
  when 'BRA' then 'Brasil'
  when 'MAR' then 'Marrocos'
  when 'HAI' then 'Haiti'
  when 'SCO' then 'Escócia'
  when 'USA' then 'Estados Unidos'
  when 'PAR' then 'Paraguai'
  when 'AUS' then 'Austrália'
  when 'TUR' then 'Turquia'
  when 'GER' then 'Alemanha'
  when 'CUW' then 'Curaçao'
  when 'CIV' then 'Costa do Marfim'
  when 'ECU' then 'Equador'
  when 'NED' then 'Países Baixos'
  when 'JPN' then 'Japão'
  when 'SWE' then 'Suécia'
  when 'TUN' then 'Tunísia'
  when 'BEL' then 'Bélgica'
  when 'EGY' then 'Egito'
  when 'IRN' then 'Irã'
  when 'NZL' then 'Nova Zelândia'
  when 'ESP' then 'Espanha'
  when 'CPV' then 'Cabo Verde'
  when 'KSA' then 'Arábia Saudita'
  when 'URU' then 'Uruguai'
  when 'FRA' then 'França'
  when 'SEN' then 'Senegal'
  when 'IRQ' then 'Iraque'
  when 'NOR' then 'Noruega'
  when 'ARG' then 'Argentina'
  when 'ALG' then 'Argélia'
  when 'AUT' then 'Áustria'
  when 'JOR' then 'Jordânia'
  when 'POR' then 'Portugal'
  when 'COD' then 'RD Congo'
  when 'UZB' then 'Uzbequistão'
  when 'COL' then 'Colômbia'
  when 'ENG' then 'Inglaterra'
  when 'CRO' then 'Croácia'
  when 'GHA' then 'Gana'
  when 'PAN' then 'Panamá'
  else name
end;
